pkgname=holoiso-main
pkgver="snapshot$(date +%Y%m%d.%H%M)"
pkgdesc="HoloISO base installation"
pkgrel="1"
depends=('archlinux-keyring' 'ark' 'cheese' 'cups' 'curl' 'dolphin' 'ffmpegthumbs' 'gamescope' 'git' 'glxinfo' 'go' 'gwenview' 'hunspell' 'hunspell-en_us' 'holo-wireplumber' 'jupiter-hw-support' 'kdegraphics-thumbnailers' 'konsole' 'kwrite' 'lib32-pipewire' 'lib32-pipewire-jack' 'lib32-pipewire-v4l2' 'lib32-vulkan-radeon' 'lib32-vulkan-intel' 'mangohud' 'mesa' 'lib32-mesa' 'holoiso-updateclient' 'noto-fonts-cjk' 'pipewire' 'pipewire-alsa' 'pipewire-jack' 'wireplumber' 'pipewire-pulse' 'pipewire-v4l2' 'plasma-meta' 'plasma-nm' 'print-manager' 'rz608-fix-git' 'spectacle' 'steam-jupiter-stable' 'steamdeck-kde-presets' 'tar' 'ufw' 'vlc' 'vulkan-intel' 'vulkan-radeon' 'yay' 'wget' 'zsh' 'xbindkeys')
arch=("x86_64")

package() {
    holoiso_codename="Stable ($(echo $RANDOM | md5sum | head -c 10; echo;))"
    mkdir -p "${pkgdir}/usr/bin"
    mkdir -p "${pkgdir}/etc"
    mkdir -p "${pkgdir}/etc/systemd/logind.conf.d"
    mkdir -p "${pkgdir}/etc/udev"    
    mkdir -p "${pkgdir}/etc/udev/rules.d"    
    mkdir -p "${pkgdir}/usr/lib/systemd/system"
    mkdir -p "${pkgdir}/etc/skel/Desktop" 
    mkdir -p "${pkgdir}/etc/xdg/autostart"
    mkdir -p "${pkgdir}/usr/bin/steamos-polkit-helpers"
    mkdir -p "${pkgdir}/etc/pacman.d"
    cp "${srcdir}/holomirror" "${pkgdir}/etc/pacman.d/holo_mirrorlist"
    cp "${srcdir}/99-oxpgamepad.rules" "${pkgdir}/etc/udev/rules.d/99-oxpgamepad.rules" 
    cp "${srcdir}/holoiso-reboot-tracker.service" "${pkgdir}/usr/lib/systemd/system/holoiso-reboot-tracker.service"       
    cp "${srcdir}/steamos-session-select" "${pkgdir}/usr/bin/steamos-session-select"
    cp "${srcdir}/holoiso-gamescope-power" "${pkgdir}/usr/bin/holoiso-gamescope-power"
    cp "${srcdir}/holoiso-reboot-tracker" "${pkgdir}/usr/bin/holoiso-reboot-tracker"
    cp "${srcdir}/holoiso-desktop-orientation" "${pkgdir}/usr/bin/holoiso-desktop-orientation"
    cp "${srcdir}/steamos-select-branch" "${pkgdir}/usr/bin/steamos-select-branch"
    cp "${srcdir}/jupiter-controller-update" "${pkgdir}/usr/bin/jupiter-controller-update"
    cp "${srcdir}/jupiter-biosupdate" "${pkgdir}/usr/bin/jupiter-biosupdate"
    cp "${srcdir}/holoiso-disable-sessions" "${pkgdir}/usr/bin/holoiso-disable-sessions"  
    cp "${srcdir}/holoiso-enable-sessions" "${pkgdir}/usr/bin/holoiso-enable-sessions"
    cp "${srcdir}/steamos-priv-write" "${pkgdir}/usr/bin/steamos-polkit-helpers/steamos-priv-write"      
    cp "${srcdir}/recoveryinit" "${pkgdir}/usr/bin/recoveryinit"      
    cp "${srcdir}/osinfo" "${srcdir}/osinfo_tmp"
    cp "${srcdir}/pacman.conf" "${pkgdir}/etc/pacman.conf"
    cp "${srcdir}/beta_pacman.conf" "${pkgdir}/etc/beta_pacman.conf"
    cp "${srcdir}/steamos-gamemode.desktop" "${pkgdir}/etc/skel/Desktop/steamos-gamemode.desktop"
    cp "${srcdir}/desktopshortcuts.desktop" "${pkgdir}/etc/xdg/autostart/desktopshortcuts.desktop"
    cp "${srcdir}/holoiso-firstboot-config" "${pkgdir}/usr/bin/holoiso-firstboot-config"
    cp "${srcdir}/holoiso-grub-update" "${pkgdir}/usr/bin/holoiso-grub-update"
    sed -i "s/snapshotver/snapshot$(date +%Y%m%d.%H%M)/g" osinfo_tmp
    sed -i "s/versionver/3.3/g" osinfo_tmp
    sed -i "s/buildver/${holoiso_codename}/g" osinfo_tmp
    cp "${srcdir}/osinfo_tmp" "${pkgdir}/etc/os-release"
    rm "${srcdir}/osinfo_tmp"
    cp "${srcdir}/holoiso-branch" "${pkgdir}/etc/holoiso-branch"
    cp "${srcdir}/logind.conf.d/suspend.conf" "${pkgdir}/etc/systemd/logind.conf.d/suspend.conf"
    chmod +x "${pkgdir}/usr/bin/steamos-session-select"
    chmod +x "${pkgdir}/usr/bin/jupiter-controller-update" 
    chmod +x "${pkgdir}/usr/bin/jupiter-biosupdate"   
    chmod +x "${pkgdir}/usr/bin/recoveryinit"  
    chmod +x "${pkgdir}/usr/bin/holoiso-reboot-tracker" 
    chmod +x "${pkgdir}/usr/bin/holoiso-gamescope-power"
    chmod +x "${pkgdir}/usr/bin/holoiso-disable-sessions"
    chmod +x "${pkgdir}/usr/bin/steamos-select-branch"
    chmod +x "${pkgdir}/usr/bin/holoiso-enable-sessions"
    chmod +x "${pkgdir}/etc/skel/Desktop/steamos-gamemode.desktop"
    chmod +x "${pkgdir}/etc/xdg/autostart/desktopshortcuts.desktop"
    chmod +x "${pkgdir}/usr/bin/holoiso-firstboot-config"
    chmod +x "${pkgdir}/usr/bin/steamos-polkit-helpers/steamos-priv-write"
    chmod 0644 "${pkgdir}/usr/lib/systemd/system/holoiso-reboot-tracker.service"
    chmod +x "${pkgdir}/usr/bin/holoiso-desktop-orientation"
    chmod +x "${pkgdir}/usr/bin/holoiso-grub-update"
    echo "Release output:"
    cat "${pkgdir}/etc/os-release"
}

