#!/bin/bash
INT_DISPLAY=$(xrandr | awk '/\<connected\>/ {print $1}' | grep eDP | head -n1)
source holoiso-devicequirk-set

if [ -z "$HOLOISO_X11_ROTATION" ]; then
    echo "Ignoring anything. Assume normal rotation"
else
    xrandr --output ${INT_DISPLAY} --rotate $HOLOISO_X11_ROTATION
fi