#!/bin/zsh
# Should be ran everytime user logs into desktop

if [[ $EUID -ne 0 ]];
then
    exec pkexec --disable-internal-agent "$0" "$@"
fi

# Remove shortcuts to be safe
sudo rm /home/$USER/Desktop/steamos-gamemode.desktop

# Copy actual shortcuts in:
sudo cp /etc/skel/Desktop/steamos-gamemode.desktop /home/$USER/Desktop/steamos-gamemode.desktop

# Permissions
sudo chmod +x /home/$USER/Desktop/steamos-gamemode.desktop