#!/bin/zsh
if [[ $EUID -ne 0 ]];
then
    exec pkexec --disable-internal-agent "$0" "$@"
fi
echo "Enabling session switching and autologin..."
mv /home/holoiso-autologin.conf /etc/sddm.conf.d/autologin.conf
echo "Done!"
