#!/bin/bash
if [[ $EUID -ne 0 ]];
then
    echo "Please run this as superuser or sudo."
    exit 0
fi

HWID=$(cat /sys/devices/virtual/dmi/id/product_name | tr -d '[:space:]')
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    --gamescope_rotation)
    OPTIONS_GR="left:right:normal:upsidedown"
    if [[ ":$OPTIONS_GR:" =~ ":$2:"  ]]; then
        GAMESCOPE_ORIENTATION="--force-panel-type external --force-external-orientation $2"
    else
        echo "Unrecognized value for Gamescope orientation Usage: \"left:right:normal:upsidedown\""
        exit 0
    fi
    shift # past argument
    shift # past value
    ;;
    --gamescope_resolution)
    if [[ "$2" == *"x"* ]]; then
        GAMESCOPE_RESOLUTION="-w $(echo $2 | cut -d 'x' -f 1) -h $(echo $2 | cut -d 'x' -f 2)"
    else
        echo "Resolution must be specified like this: 1920x1080"
        exit 0
    fi
    shift # past argument
    shift # past value
    ;;
    --desktop_rotation)
    OPTIONS_XR="left:right:normal:inverted"
    if [[ ":$OPTIONS_XR:" =~ ":$2:"  ]]; then
        XRANDR_ORIENTATION="$2"
    else
        echo "Unrecognized value for Desktop orientation Usage: \"left:right:normal:inverted\""
        exit 0
    fi
    shift # past argument
    shift # past value
    ;;
    --grub_additional_options)
    GRUB_OPTIONS="$2"
    shift # past argument
    shift # past value
    ;;
    --help)
    echo -e "HoloISO Device Quirk generator\n\nOptions:\nGamemode options:\n--gamescope_rotation: Rotates the internal display in gamemode (left, right, normal, upsidedown)\n--gamescope_resolution: Adds custom resolution for gamescope (-w 1920 -h 1080)\n\nDesktop options:\n--desktop_rotation: Rotates the internal display in Plasma (left, right, normal, inverted)\n\nGeneral and additional options:\n--grub_additional_options: Adds additional GRUB options on next bootloader rebuild"
    exit 0
    ;;
    *)    # unknown option
    echo "Unknown option: $1, use --help "
    exit 1
    ;;
esac
done

if [[ -z "$GAMESCOPE_ORIENTATION" ]] && [[ -z "$GAMESCOPE_RESOLUTION" ]] && [[ -z "$XRANDR_ORIENTATION" ]] && [[ -z "$GRUB_OPTIONS" ]]; then
    echo "Whatcha gonna generate with nothing? :)"
    exit 0
fi

mkdir -p /usr/lib/holoiso-hwsupport/customdevicequirks/
QUIRKPATH="/usr/lib/holoiso-hwsupport/customdevicequirks/${HWID}.sh"
echo -e '#!/bin/bash' > $QUIRKPATH
echo -e "#HoloISO Quirkfile for $HWID\n" >> $QUIRKPATH

if [[ ! -z "$GAMESCOPE_ORIENTATION" ]]; then
    echo -e "export HOLOISO_GAMESCOPE_ADDITIONAL_OPTIONS=\"$GAMESCOPE_ORIENTATION\"" >> $QUIRKPATH
fi
if [[ ! -z "$GAMESCOPE_RESOLUTION" ]]; then
    echo -e "export HOLOISO_GAMESCOPE_RES=\"$GAMESCOPE_RESOLUTION\"" >> $QUIRKPATH
fi
if [[ ! -z "$XRANDR_ORIENTATION" ]]; then
    echo -e "export HOLOISO_X11_ROTATION=\"$XRANDR_ORIENTATION\"" >> $QUIRKPATH
fi
if [[ ! -z "$GRUB_OPTIONS" ]]; then
    echo -e "export HOLOISO_GRUB_ADDITIONAL_CMDLINEOPTIONS=\"$GRUB_OPTIONS\"" >> $QUIRKPATH
fi
echo -e "export HOLOISO_DEVICE_TYPE=\"$HWID\"" >> $QUIRKPATH