#!/bin/zsh
# Should be ran everytime user logs into desktop

# Remove shortcuts to be safe
sudo rm /home/$USER/Desktop/steam.desktop
sudo rm /home/$USER/Desktop/steamos-gamemode.desktop

# Copy actual shortcuts in:
sudo ln -s /usr/share/applications/steam.desktop /home/$USER/Desktop/steam.desktop
sudo cp /etc/skel/Desktop/steamos-gamemode.desktop /home/$USER/Desktop/steamos-gamemode.desktop

# Permissions
sudo chmod +x /home/$USER/Desktop/steam.desktop
sudo chmod +x /home/$USER/Desktop/steamos-gamemode.desktop

# Win600 and others screen orientation
sudo holoiso-desktop-orientation